"""initial_schema

Revision ID: ce109531ee60
Revises: 
Create Date: 2026-03-06 11:49:19.813000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce109531ee60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classified_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_event_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classified_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classified_events_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_classified_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_classified_events_source'), ['source'], unique=False)

    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_events_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_events_source'), ['source'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_timestamp'), ['timestamp'], unique=False)

    op.create_table('source_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('records_last_run', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_status_name'), ['name'], unique=True)

    op.create_table('dimension_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('raw_values', sa.JSON(), nullable=False),
    sa.Column('z_scores', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dimension_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dimension_scores_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimension_scores_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimension_scores_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_dimension_scores_dimension'))

    op.drop_table('dimension_scores')
    with op.batch_alter_table('source_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_status_name'))

    op.drop_table('source_status')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_timestamp'))

    op.drop_table('scores')
    with op.batch_alter_table('raw_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_events_source'))
        batch_op.drop_index(batch_op.f('ix_raw_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_raw_events_collected_at'))

    op.drop_table('raw_events')
    with op.batch_alter_table('classified_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classified_events_source'))
        batch_op.drop_index(batch_op.f('ix_classified_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_classified_events_dimension'))

    op.drop_table('classified_events')
    # ### end Alembic commands ###
